# Travis CI build file for Kitura-CredentialsHTTP.
# Kitura runs on OS X and Linux (Ubuntu v15.10).

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/

notifications:
  slack:
    secure: "M8Ny2grDIwv+jTRTPIlYRiak05HwrGMjXaEJYk/jagTYYZcUL/4m1ebPX5zE768o1C/ALqIzWDX82Vcoy9xlOgtwB/UaOy5JNxj9SxJe7qGHJ6VzEx8rfnKFgYaOC/OA3LkZjA8ntMbzwwH60RDmHESgCihqaLe5wHyNV9XicZqqKmUC3umw4rG4dSu8+1o2evGM2uaCal93HrSSKl23KlotdSxf7sEHxUrAP7jDIoYeHsIPlUyoSUQFKcBPKqBdRl7ENabW7ZAGhy7oU2W0EvWgyF9ZJ+4x+wXzQZ05ruTXd1rPw5JD7s3KuTSQ3wsIox7YWszwRaypN1sGX7Lsb9N7dsEDfra/MbBrfiVHHzCHIURhREfBMbsoXaQ90wQLS/S5Mlvc6w6KafrjkvzrlrLMP+19oF/yd6onCUOFry3tkvva0+MXf5K3+UVU6+xflCFpYZLz0h3nK5XbVvyBNEZQFrHlUKRs0jVLJUO7hhkzTjgw8cX4P0ASu4bJ26N7uCnylQTfDgXs79twDUT4MKr82FaD2efk14BSgvXq4+aXRPzqLsqRwkNTwUPJM3yMvrRI9U2kEHAshGAGOYUnfP/ekGOmmzT9i0sYHddZekOWf9Xm5vsKok8oWr6MmcVGeyeAmzvz8gh1CTRM9vGbE1wf3i38zrl2GBRDCKPhifQ="

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
    - os: osx
      osx_image: xcode8
      sudo: required

before_install:
  - git submodule init
  - git submodule update
  - cd Kitura-Build && git checkout master && cd $TRAVIS_BUILD_DIR

script:
  - echo ">> Let's build and test the '$TRAVIS_BRANCH' branch for Kitura-CredentialsHTTP."
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./Kitura-Build/run_kitura_ubuntu_container.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR Kitura-CredentialsHTTP ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Kitura-Build/build_kitura_package.sh ; fi
  - echo ">> Build and tests completed. See above for status."
